# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'pipelines-dotnet-core.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'pipelines-dotnet-core.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'pipelines-dotnet-core.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'